#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-magento.test}
VERSION=${2:-2.4.5-p1}
EDITION=${3:-community}

curl -s https://raw.githubusercontent.com/sozo-design/magento2-docker/master/lib/template | bash
# local testing
# ../lib/template | bash


COMPOSER_HOME=$(composer config --global --list | grep '\[home\]' | awk '{print $2}')

# Setup required information and save in the local.env file
read -p "Enter your local composer home directory: " COMPOSER_HOME
read -p "Enter your GitHub SSH Private Key location for composer: " GITHUB_SSH_PRIVATE_KEY
cat '.docker/local.env.sample' > ".docker/local.env"
sed -ri -e 's!{{COMPOSER_HOME}}!'"$COMPOSER_HOME"'!' \
  -e 's!{{GITHUB_SSH_PRIVATE_KEY}}!'"$GITHUB_SSH_PRIVATE_KEY"'!' \
  ".docker/local.env"

# Update env references
sed -i -e "s/{{PROJECT_NAME}}/${VERSION//./}/g" .docker/config.env
sed -i -e "s/{{LOCAL_DOMAIN}}/$DOMAIN/g" .docker/config.env
sed -i -e "s/{{LOCAL_DOMAINS}}/$DOMAIN/g" .docker/config.env
sed -i -e "s/{{PROJECT_NAME}}/${VERSION//./}/g" DOCKER.md
sed -i -e "s/{{LOCAL_DOMAIN}}/$DOMAIN/g" DOCKER.md

# &&'s are used below otherwise freshsetup script fails/errors after bin/download
bin/download-m2 "${VERSION}" "${EDITION}" && bin/setup "${DOMAIN}"