#!/usr/bin/env bash

# Download the bin files
curl -s https://raw.githubusercontent.com/sozo-design/magento2-docker/master/lib/downloader | bash -s https://github.com/sozo-design/magento2-docker/compose

# Move files to the correct locations
chmod +x -R compose/bin/

mv compose/bin ./bin
mv compose/.docker ./.docker
mv compose/docker-compose.yaml ./docker-compose.yaml
mv compose/environments ./environments
mv compose/DOCKER.md ./DOCKER.md

mkdir -p magento
rm -rf compose
