#!/usr/bin/env bash

# Download the bin files
curl -s https://raw.githubusercontent.com/sozo-design/magento2-docker/master/lib/downloader | bash -s https://github.com/sozo-design/magento2-docker/compose

# Move files to the correct locations
chmod +x compose/bin/*
mv compose/* ./
rm -rf compose

# Environments?