#!/usr/bin/env bash

# Download the bin files
curl -s https://raw.githubusercontent.com/sozo-design/magento2-docker/master/lib/downloader | bash -s https://github.com/sozo-design/magento2-docker/compose

# Move files to the correct locations
chmod +x compose/bin/*
mv compose/* ./
mkdir -p magento
rm -rf compose

# Environment files used later for linking into a container
mkdir -p environments/docker/wp/
touch environments/docker/wp/wp-config.php