version: '2.1'
services:
  cron:
    hostname: "cron.${LOCAL_DOMAIN}"
    build:
      context: '.docker/cron/'
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    extends: generic
    volumes:
      - 'mymagento-magento-sync:/app:delegated'
      - './environments/docker/app/etc/config.php:/app/app/etc/config.php'
      - './environments/docker/app/etc/env.php:/app/app/etc/env.php'
    networks:
      magento:
        aliases:
          - "cron.${LOCAL_DOMAIN}"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy

  db:
    hostname: "db.${APP_DOMAIN}"
    image: 'mysql:8.0'
    environment:
      - "MYSQL_ROOT_PASSWORD=magento2"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - 'mymagento-magento-sync:/app:delegated'
      - 'mymagento-magento-db:/var/lib/mysql'
      - './.docker/DB/setup.sql:/docker-entrypoint-initdb.d/01-setup.sql'
      - './.docker/DB/config.cnf:/etc/mysql/conf.d/config.cnf'
    healthcheck:
      test: 'mysqladmin ping -uroot -pmagento -h localhost'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - "db.${APP_DOMAIN}"

  redis:
    hostname: "redis.${APP_DOMAIN}"
    image: 'redis:5.0'
    volumes:
      - 'mymagento-magento-sync:/app:delegated'
    ports:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - "redis.${APP_DOMAIN}"

  elasticsearch:
    hostname: "elasticsearch.${APP_DOMAIN}"
    image: elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - index.blocks.read_only_allow_delete
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - "elasticsearch.${APP_DOMAIN}"

  fpm:
    hostname: "fpm.${APP_DOMAIN}"
    build:
      context: '.docker/PHP/'
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    extends: generic
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - 'mymagento-magento-sync:/app:delegated'
      - './environments:/environments:delegated'
      - './dev/composerTidy.js:/dev/composerTidy.js:delegated'
      - './environments/docker/app/etc/config.php:/app/app/etc/config.php:cached'
      - './environments/docker/app/etc/env.php:/app/app/etc/env.php:cached'
      - '~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached'
      - "${COMPOSER_HOME}:/var/www/.composer:cached"
    environment:
      - UPSTREAM_HOST=fpm
      - UPSTREAM_PORT=9000
    networks:
      magento:
        aliases:
          - "fpm.${APP_DOMAIN}"
    depends_on:
      db:
        condition: service_healthy

  web:
    hostname: "web.${APP_DOMAIN}"
    build: '.docker/Web/'
    extends: generic
    volumes:
      - 'mymagento-magento-sync:/app:delegated'
    environment:
      - "VIRTUAL_HOST=${APP_DOMAIN}"
      - VIRTUAL_PORT=80
      - UPSTREAM_HOST=web
      - UPSTREAM_PORT=80
      - HTTPS_METHOD=noredirect
      - MAGENTO_RUN_MODE=developer
      - DEBUG=false
      - WITH_XDEBUG=0
#      - UPLOAD_MAX_FILESIZE=64M
#      - FPM_HOST=fpm
#      - FPM_PORT=9000
#      - MAGENTO_ROOT=/app
#      - UPSTREAM_HOST=web
#      - UPSTREAM_PORT=8080
#      - MFTF_UTILS=0
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
    ports:
      - '8080:8080'
    networks:
      magento:
        aliases:
          - "web.${APP_DOMAIN}"
    healthcheck:
      test: exit 0
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      fpm:
        condition: service_started

  tls:
    hostname: "tls.${APP_DOMAIN}"
    build: '.docker/Tls/'
    extends: generic
    volumes:
      - 'mymagento-magento-sync:/app:delegated'
    networks:
      magento:
        aliases:
          - "${APP_DOMAIN}"
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=web
      - UPSTREAM_PORT=8080
      - WITH_XDEBUG=0
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      web:
        condition: service_started
#        varnish:
#          condition: service_started

  #  varnish:
  #    hostname: "varnish.${APP_DOMAIN}"
  #    image: 'magento/magento-cloud-docker-varnish:6.2'
  #    networks:
  #      magento:
  #        aliases:
  #          - "${APP_DOMAIN}"
  #    volumes:
  #      - './.docker/Varnish/default.vcl:/etc/varnish/default.vcl'
  #    depends_on:
  #      web:
  #        condition: service_healthy

  generic:
    hostname: "generic.${APP_DOMAIN}"
    build: '.docker/Generic/'
    env_file: ./.docker/config.env
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip sodium redis xsl blackfire'

  mailhog:
    hostname: "mailhog.${APP_DOMAIN}"
    image: 'ghcr.io/sozo-design/magento2-mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      magento:
        aliases:
          - "mailhog.${APP_DOMAIN}"

  rabbitmq:
    hostname: "rabbitmq.${LOCAL_DOMAIN}"
    image: 'rabbitmq:3.9-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - mymagento-rabbitmq-data:/var/lib/rabbitmq
    networks:
      magento:
        aliases:
          - "rabbitmq.${LOCAL_DOMAIN}"
    healthcheck:
      test: 'rabbitmq-diagnostics -q ping'
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  mymagento-magento-sync:
    driver_opts:
      type: none
      device: ${PWD}/magento
      o: bind
  mymagento-magento-db: {  }
  mymagento-rabbitmq-data: { }
networks:
  magento:
    driver: bridge
